apiVersion: v1
kind: Service
metadata:
  labels:
    app: dsb
  name: dsb-ui-deployment
  namespace: botva
spec:
  ports:
    - nodePort: 30888
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dsb
  sessionAffinity: None
  type: NodePort
